### ISSUE TITLE
twitch_vod_fetch: final file move fails when --ytdl-output-format specifies non-existing directory

### ISSUE THREAD

**Issue by X1011** [mk-fg/fgtk#16]
In the same vain as #7, the script fails when attempting to move the output file to its final destination when the destination directory does not yet exist. Understandably, you may not expect to be given a non-existing directory before you implemented `--ytdl-output-format`, but now it may be desirable, seeing as said option can be used to create directories dynamically, or at least youtube-dl can be used in that way. For example, here is what I just tried:
```
$ twitch_vod_fetch --aria2c-opts "max-concurrent-downloads=2 lowest-speed-limit=10K rpc-listen-all" -o '%(uploader)s/2018-10-10 %(title)s.ts' https://www.twitch.tv/videos/321031441 -s 9:57 -l 19:10
2018-12-08 04:01:14 :: INFO :: --- Downloading VoD vod-001.mp4 (final-name='Nico/2018-10-10 sister nico - happy hallowmeme - !goal !sub.ts', url=https://www.twitch.tv/videos/321031441)
2018-12-08 04:01:27 :: INFO :: 

  ------ Started 115 downloads, last gid: 000115 ------  

                                                                                                                                   
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
Traceback (most recent call last):
  File "/home/dan/.local/apps/miniconda3/lib/python3.7/shutil.py", line 557, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'vod-001.mp4' -> 'Nico/2018-10-10 sister nico - happy hallowmeme - !goal !sub.ts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/bin/vendor/twitch_vod_fetch", line 930, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "/home/dan/bin/vendor/twitch_vod_fetch", line 926, in main
    loop, conf, vod_queue, list_formats_only=opts.ytdl_list_formats ))
  File "/home/dan/.local/apps/miniconda3/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/home/dan/bin/vendor/twitch_vod_fetch", line 271, in vod_fetch
    try: await fetch(url, prefix, info_suffix=info_suffix)
  File "/home/dan/bin/vendor/twitch_vod_fetch", line 189, in _wrapper
    return await func(self, ctx, *args, **kws)
  File "/home/dan/bin/vendor/twitch_vod_fetch", line 783, in get
    shutil.move(file_dst_path, file_dst_done, copy_function=shutil.copy)
  File "/home/dan/.local/apps/miniconda3/lib/python3.7/shutil.py", line 571, in move
    copy_function(src, real_dst)
  File "/home/dan/.local/apps/miniconda3/lib/python3.7/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/dan/.local/apps/miniconda3/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'Nico/2018-10-10 sister nico - happy hallowmeme - !goal !sub.ts'
Command exited with non-zero status 1
```
After this, I created the directory manually and re-ran the command, and it finished normally.

Granted, this is a minor inconvenience for my use case, as I am only creating a directory for each channel, and I understand if this feature would be out of scope for this script. Regardless, thank you for the script; it does work very nicely. :+1:

**Comment by mk-fg** [comment]
Thanks.
It's a one-liner fix anyway, so no big deal :)
Should be fixed in e17b4bc.
