### ISSUE TITLE
vfat_shuffler: Listing crashes with KeyError: '.'

### ISSUE THREAD

**Issue by cweiske** [mk-fg/fgtk#20]
vfat_shuffler crashes when listing files at entry ".", which is the current folder:

```
cweiske:~> sudo ./bin/vfat_shuffler.py /media/cweiske --list
[sudo] Passwort für cweiske: 
Traceback (most recent call last):
  File "./bin/vfat_shuffler.py", line 667, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./bin/vfat_shuffler.py", line 647, in main
    paths = [op_navigate(fs, path)]
  File "./bin/vfat_shuffler.py", line 428, in op_navigate
    for k in filter(None, slugs): path = path[k]
  File "./bin/vfat_shuffler.py", line 263, in __getitem__
    raise KeyError(name)
KeyError: '.'
```

**Comment by mk-fg** [comment]
Thanks. Should be fixed in f6a8516.
Probably never ran it on a mountpoint root like that myself, I guess.

**Comment by cweiske** [comment]
Listing a mountpoint without specifying a path works fine now:
```
sudo ./bin/vfat_shuffler --umount /media/cweiske/CWEISKEOUYA/
[      0] {name}.{ext}
[  43075] 01 - Dont Tell Me That Its Over.ogg
[  43419] 01 - Ich bin hier.ogg
[  43809] 01 - My Lucky Day.ogg
```

(It's quite slow, but that is not relevant now [10,636s for a directory with 108 files])

**Comment by cweiske** [comment]
Thank you for the quick bugfix!
